---
# tasks file for ansible-role-basic-apache-container
- include_tasks: "setup-centos.yml"
- include_tasks: "install-docker.yml"
- name: Copy website file template
  template:
    src: "{{ file_template }}"
    dest: "/home/{{ system_user }}/index.html"
- name: Create Apache container
  docker_container:
    name: webapp
    image: httpd
    ports:
        - "{{ webapp_port }}:{{ apache_port }}"
    volumes:
        - "/home/{{ system_user }}/index.html:/usr/local/apache2/htdocs/index.html"